[project]
name = "Pharmacy_distributor"
version = "1.0.0"
authors = [{name = "Ivan Zakharenkau", email = "vawashop@gmail.com"}]

[tool.pytest.ini_options]
pythonpath = ["src"]
testpaths = ["tests"]

[tool.coverage.run]
source = ["src"]
omit = [
    "*/*/__main__.py",
    "*/*/__init__.py",
]

[project.optional-dependencies]
dev = [
    "pytest>=7.4.0",
    "pytest-cov>=4.1.0",
]
docs = [
    "sphinx>=7.0.0",
]